"""
Deployment Service
Business logic for deployment operations
"""
import logging
from typing import List
from datetime import datetime
from app.models.deployment import Deployment, DeploymentStatus
from app.repositories.deployment_repository import DeploymentRepository
from app.core.exceptions import DeploymentNotFoundError, DeploymentFailedError

logger = logging.getLogger(__name__)


class DeploymentService:
    """Service for deployment business logic"""
    
    def __init__(self, repository: DeploymentRepository):
        self.repository = repository
    
    def create_deployment(
        self,
        application: str,
        version: str,
        environment: str,
        deployed_by: str = "system"
    ) -> Deployment:
        """Create a new deployment"""
        logger.info(
            f"Creating deployment for {application} v{version} to {environment}"
        )
        
        deployment = Deployment(
            id="",  # Will be generated by repository
            application=application,
            version=version,
            environment=environment,
            deployed_by=deployed_by,
            status=DeploymentStatus.PENDING
        )
        
        return self.repository.create(deployment)
    
    def get_deployment(self, deployment_id: str) -> Deployment:
        """Get deployment by ID"""
        deployment = self.repository.get_by_id(deployment_id)
        if not deployment:
            raise DeploymentNotFoundError(deployment_id)
        return deployment
    
    def list_deployments(self, page: int = 1, page_size: int = 20) -> tuple[List[Deployment], int]:
        """List deployments with pagination"""
        skip = (page - 1) * page_size
        deployments = self.repository.list_all(skip=skip, limit=page_size)
        total = self.repository.count()
        return deployments, total
    
    def start_deployment(self, deployment_id: str) -> Deployment:
        """Start a deployment"""
        deployment = self.get_deployment(deployment_id)
        
        logger.info(f"Starting deployment {deployment_id}")
        deployment.status = DeploymentStatus.IN_PROGRESS
        
        return self.repository.update(deployment)
    
    def complete_deployment(self, deployment_id: str, success: bool = True, error: str = None) -> Deployment:
        """Complete a deployment"""
        deployment = self.get_deployment(deployment_id)
        
        deployment.status = DeploymentStatus.SUCCESS if success else DeploymentStatus.FAILED
        deployment.completed_at = datetime.utcnow()
        
        if error:
            deployment.error_message = error
        
        logger.info(
            f"Deployment {deployment_id} completed with status {deployment.status}"
        )
        
        return self.repository.update(deployment)
